Update gradle.yml

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -9,8 +9,6 @@ on:
 jobs:
   build:
     runs-on: ubuntu-latest
-    permissions:
-      contents: read
 
     steps:
       - uses: actions/checkout@v4
@@ -27,7 +25,8 @@ jobs:
       - name: Start SUT
         run: |
           java -jar ./artifacts/app-card-delivery.jar &
-          sleep 5
+          sleep 10
+          curl -I http://localhost:9999 || echo "Failed to connect"
 
       - name: Run tests
         run: ./gradlew test --info -Dselenide.headless=true
